AllCops:
  TargetRubyVersion: 3.1
  # enable sometimes
  SuggestExtensions: false
  Exclude:
    - "bin/*"
    - "doc"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "sdk/**/*"
    - "swagger/**/*"
    - "tmp/**/*"
    - "coverage/**/*"
    - "log/**/*"
    - "docker/**/*"
require:
  - rubocop-rspec
  - rubocop-performance
Metrics/MethodLength:
  Max: 999
Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: always_inspect
Style/Documentation:
  Enabled: false
Style/Semicolon:
  Enabled: true
  AllowAsExpressionSeparator: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/WordArray:
  EnforcedStyle: brackets
Style/SymbolArray:
  EnforcedStyle: brackets
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Metrics/ClassLength:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
  Enabled: true
Layout/ElseAlignment:
  Enabled: true
Style/Alias:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: indented
  IndentationWidth: ~
Style/EmptyMethod:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Layout/ParameterAlignment:
  Enabled: true
Layout/ClosingParenthesisIndentation:
  Enabled: true
Layout/MultilineMethodCallBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical
Lint/SuppressedException:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: true
Layout/EmptyLines:
  Enabled: true
Style/FormatStringToken:
  Enabled: false
Layout/IndentationWidth:
  Enabled: true
Lint/AmbiguousBlockAssociation:
  Enabled: false
Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent
  IndentationWidth: ~
Metrics/ModuleLength:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/LineEndConcatenation:
  Enabled: true
  SafeAutoCorrect: false
Style/GlobalVars:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/TrailingUnderscoreVariable:
  Enabled: false
Layout/CaseIndentation:
  Enabled: false
Lint/UnderscorePrefixedVariableName:
  Enabled: true
Layout/LineLength:
  Enabled: true
  Max: 230
Style/ZeroLengthPredicate:
  Enabled: false
Style/Next:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/CommentAnnotation:
  Enabled: false
Style/InverseMethods:
  Enabled: false
Layout/FirstArgumentIndentation:
  Enabled: true
  EnforcedStyle: consistent
  IndentationWidth: ~
Style/ConditionalAssignment:
  Enabled: true
Style/AsciiComments:
  Enabled: false
Style/StructInheritance:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Layout/HeredocIndentation:
  Enabled: true
Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true
Bundler/OrderedGems:
  Enabled: false
Style/MultipleComparison:
  Enabled: false
Style/EmptyLiteral:
  Enabled: true
Metrics/BlockNesting:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Layout/AssignmentIndentation:
  Enabled: true
  IndentationWidth: ~
Layout/MultilineArrayBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical
Security/MarshalLoad:
  Enabled: false
Lint/NonLocalExitFromIterator:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Lint/ParenthesesAsGroupedExpression:
  Enabled: true
Style/SpecialGlobalVars:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/HashTransformKeys:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Lint/UriEscapeUnescape:
  Enabled: false
Lint/Void:
  Enabled: false
Naming/BinaryOperatorParameterName:
  Enabled: true
Gemspec/OrderedDependencies:
  Enabled: false
Style/TrailingMethodEndStatement:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation
Lint/ToJSON:
  Enabled: false
Layout/RescueEnsureAlignment:
  Enabled: true
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
Style/SlicingWithRange:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/DuplicateRescueException:
  Enabled: true
Lint/EmptyConditionalBody:
  Enabled: true
Lint/FloatComparison:
  Enabled: true
Lint/OutOfRangeRegexpRef:
  Enabled: true
Lint/SelfAssignment:
  Enabled: true
Lint/TopLevelReturnWithArgument:
  Enabled: true
Lint/UnreachableLoop:
  Enabled: false
Style/AccessorGrouping:
  Enabled: true
Style/ArrayCoercion:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/CaseLikeIf:
  Enabled: true
Style/ExplicitBlockArgument:
  Enabled: true
Style/GlobalStdStream:
  Enabled: true
Style/HashAsLastArrayItem:
  Enabled: false
Style/HashLikeCase:
  Enabled: true
Style/OptionalBooleanParameter:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantFileExtensionInRequire:
  Enabled: false
Style/SingleArgumentDig:
  Enabled: true
Style/StringConcatenation:
  Enabled: false
Lint/DuplicateRequire:
  Enabled: true
Lint/EmptyFile:
  Enabled: true
Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true
Lint/UselessMethodDefinition:
  Enabled: true
Style/CombinableLoops:
  Enabled: true
Style/RedundantSelfAssignment:
  Enabled: true
Style/SoleNestedConditional:
  Enabled: true
Layout/BeginEndAlignment:
  Enabled: true
Lint/ConstantDefinitionInBlock:
  Enabled: true
Lint/IdentityComparison:
  Enabled: true
Lint/UselessTimes:
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
Lint/EmptyBlock:
  Enabled: true
Lint/ToEnumArguments:
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Style/ArgumentsForwarding:
  Enabled: false
Style/DocumentDynamicEvalDefinition:
  Enabled: true
Style/SwapValues:
  Enabled: true
Lint/DuplicateBranch:
  Enabled: true
Lint/EmptyClass:
  Enabled: true
# pretty silly rule
Lint/NoReturnInBeginEndBlocks:
  Enabled: false
Lint/UnexpectedBlockArity:
  Enabled: true
Style/CollectionCompact:
  Enabled: true
Style/NegatedIfElseCondition:
  Enabled: true
Style/NilLambda:
  Enabled: true
Style/RedundantArgument:
  Enabled: true
Layout/SpaceBeforeBrackets:
  Enabled: false
Lint/AmbiguousAssignment:
  Enabled: true
Style/HashExcept:
  Enabled: true
Lint/DeprecatedConstants:
  Enabled: true
Lint/LambdaWithoutLiteralBlock:
  Enabled: true
Lint/RedundantDirGlobSort:
  Enabled: true
Style/EndlessMethod:
  Enabled: true
Lint/NumberedParameterAssignment:
  Enabled: true
Lint/OrAssignmentToConstant:
  Enabled: true
Lint/SymbolConversion:
  Enabled: true
Lint/TripleQuotes:
  Enabled: true
Style/IfWithBooleanLiteralBranches:
  Enabled: true
Style/HashConversion:
  Enabled: true
RSpec/MultipleExpectations:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/ExampleWording:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/VariableName:
  Enabled: false
RSpec/Be:
  Enabled: false
RSpec/EmptyExampleGroup:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
RSpec/StubbedMock:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
RSpec/ScatteredSetup:
  Enabled: false
# possible we'll enable it in future
RSpec/VariableDefinition:
  Enabled: false
RSpec/LetSetup:
  Enabled: true
Performance/InefficientHashSearch:
  Enabled: true
Performance/RedundantMatch:
  Enabled: true
Performance/TimesMap:
  Enabled: false
Performance/ReverseFirst:
  Enabled: true
Performance/AncestorsInclude:
  Enabled: true
Performance/BigDecimalWithNumericArgument:
  Enabled: true
Performance/BlockGivenWithExplicitBlock:
  Enabled: true
Performance/CollectionLiteralInLoop:
  Enabled: true
Performance/ConstantRegexp:
  Enabled: true
Performance/MethodObjectAsBlock:
  Enabled: true
Performance/RedundantEqualityComparisonBlock:
  Enabled: true
Performance/RedundantSortBlock:
  Enabled: true
Performance/RedundantSplitRegexpArgument:
  Enabled: true
Performance/RedundantStringChars:
  Enabled: true
Performance/SortReverse:
  Enabled: true
Performance/Squeeze:
  Enabled: true
Performance/StringInclude:
  Enabled: true
Performance/Sum:
  Enabled: true
Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
Layout/ExtraSpacing:
  Enabled: true
  AllowForAlignment: false
  AllowBeforeTrailingComments: false
  ForceEqualSignAlignment: false
Style/CommentedKeyword:
  Enabled: true
Layout/ArrayAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation
Layout/MultilineHashBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical
Layout/CommentIndentation:
  Enabled: true
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space
Layout/SpaceBeforeBlockBraces:
  Enabled: true
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space
Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: true
Style/RedundantSelf:
  Enabled: true
Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19_no_mixed_keys
Style/KeywordParametersOrder:
  Enabled: true
Style/RescueStandardError:
  Enabled: true
  EnforcedStyle: implicit
Lint/AssignmentInCondition:
  Enabled: true
  AllowSafeAssignment: true
Style/EachWithObject:
  Enabled: true
Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: true
Layout/EmptyLinesAroundClassBody:
  Enabled: true
Layout/EmptyLinesAroundBlockBody:
  Enabled: true
  EnforcedStyle: no_empty_lines
Layout/EmptyLinesAroundArguments:
  Enabled: true
Layout/EmptyLinesAroundModuleBody:
  Enabled: true
  EnforcedStyle: no_empty_lines
Layout/EmptyLinesAroundMethodBody:
  Enabled: true
Layout/EmptyLineBetweenDefs:
  Enabled: true
  AllowAdjacentOneLineDefs: false
  NumberOfEmptyLines: 1
Style/StringChars:
  Enabled: false
Performance/MapCompact:
  Enabled: true
Lint/EmptyInPattern:
  Enabled: true
Style/InPatternThen:
  Enabled: true
Style/MultilineInPatternThen:
  Enabled: true
Style/QuotedSymbols:
  Enabled: false
RSpec/IdenticalEqualityAssertion:
  Enabled: true
Layout/LineEndStringConcatenationIndentation:
  Enabled: false
Naming/InclusiveLanguage:
  Enabled: false
Lint/AmbiguousRange:
  Enabled: true
Style/RedundantSelfAssignmentBranch:
  Enabled: true
Lint/AmbiguousOperatorPrecedence:
  Enabled: true
Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: true
Lint/RequireRelativeSelfPath:
  Enabled: true
Security/IoMethods:
  Enabled: true
Style/NumberedParameters:
  Enabled: true
Style/NumberedParametersLimit:
  Enabled: true
Style/SelectByRegexp:
  Enabled: true
RSpec/ExcessiveDocstringSpacing:
  Enabled: true
RSpec/SubjectDeclaration:
  Enabled: true
Gemspec/RequireMFA:
  Enabled: true
Lint/UselessRuby2Keywords:
  Enabled: true
Style/OpenStructUse:
  Enabled: true
Performance/ConcurrentMonotonicTime:
  Enabled: true
RSpec/VoidExpect:
  Enabled: true
Naming/BlockForwarding:
  Enabled: true
Style/FileRead:
  Enabled: true
Style/FileWrite:
  Enabled: true
Style/MapToHash:
  Enabled: true
Performance/StringIdentifierArgument:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Lint/RedundantCopDisableDirective:
  Enabled: false
Style/NestedFileDirname: # new in 1.26
  Enabled: true
RSpec/BeEq: # new in 2.9.0
  Enabled: false
RSpec/BeNil: # new in 2.9.0
  Enabled: true
Lint/RefinementImportMethods: # new in 1.27
  Enabled: true
Style/RedundantInitialize: # new in 1.27
  Enabled: true
Security/CompoundHash: # new in 1.28
  Enabled: true
Style/EnvHome: # new in 1.29
  Enabled: true
Style/FetchEnvVar: # new in 1.28
  Enabled: true
Style/ObjectThen: # new in 1.28
  Enabled: true
RSpec/VerifiedDoubleReference: # new in 2.10.0
  Enabled: true
RSpec/ChangeByZero: # new in 2.11.0
  Enabled: true
Gemspec/DeprecatedAttributeAssignment: # new in 1.30
  Enabled: true
Style/MapCompactWithConditionalBlock: # new in 1.30
  Enabled: true
Layout/LineContinuationLeadingSpace: # new in 1.31
  Enabled: false
Layout/LineContinuationSpacing: # new in 1.31
  Enabled: true
Lint/ConstantOverwrittenInRescue: # new in 1.31
  Enabled: true
Lint/NonAtomicFileOperation: # new in 1.31
  Enabled: true
Lint/RequireRangeParentheses: # new in 1.32
  Enabled: true
Style/EmptyHeredoc: # new in 1.32
  Enabled: true
Style/MagicCommentFormat: # new in 1.35
  Enabled: true
RSpec/ClassCheck: # new in 2.13
  Enabled: true
RSpec/NoExpectationExample: # new in 2.13
  Enabled: false
Lint/DuplicateMagicComment: # new in 1.37
  Enabled: true
Style/OperatorMethodCall: # new in 1.37
  Enabled: true
Style/RedundantStringEscape: # new in 1.37
  Enabled: true
RSpec/SortMetadata: # new in 2.14
  Enabled: true
Style/RedundantEach: # new in 1.38
  Enabled: true
Style/ArrayIntersect: # new in 1.40
  Enabled: true
Style/ConcatArrayLiterals: # new in 1.41
  Enabled: true
Style/MapToSet: # new in 1.42
  Enabled: true
Style/MinMaxComparison: # new in 1.42
  Enabled: true
Style/RedundantConstantBase: # new in 1.40
  Enabled: true
Style/RedundantDoubleSplatHashBraces: # new in 1.41
  Enabled: true
Style/YodaExpression: # new in 1.42
  Enabled: false
RSpec/DuplicatedMetadata: # new in 2.16
  Enabled: true
RSpec/PendingWithoutReason: # new in 2.16
  Enabled: false
Gemspec/DevelopmentDependencies: # new in 1.44
  Enabled: true
Lint/UselessRescue: # new in 1.43
  Enabled: true
Metrics/CollectionLiteralLength: # new in 1.47
  Enabled: false
Style/ComparableClamp: # new in 1.44
  Enabled: true
Style/DirEmpty: # new in 1.48
  Enabled: true
Style/FileEmpty: # new in 1.48
  Enabled: true
Style/RedundantHeredocDelimiterQuotes: # new in 1.45
  Enabled: true
RSpec/RedundantAround: # new in 2.19
  Enabled: true
RSpec/SkipBlockInsideExample: # new in 2.19
  Enabled: true
RSpec/MatchArray:
  Enabled: false
Lint/DuplicateMatchPattern: # new in 1.50
  Enabled: true
Style/DataInheritance: # new in 1.49
  Enabled: true
Style/ExactRegexpMatch: # new in 1.51
  Enabled: true
Style/RedundantLineContinuation: # new in 1.49
  Enabled: true
RSpec/BeEmpty: # new in 2.20
  Enabled: true
RSpec/ContainExactly: # new in 2.19
  Enabled: true
RSpec/IndexedLet: # new in 2.20
  Enabled: false
Lint/MixedCaseRange: # new in 1.53
  Enabled: true
Lint/RedundantRegexpQuantifiers: # new in 1.53
  Enabled: true
Style/RedundantArrayConstructor: # new in 1.52
  Enabled: true
Style/RedundantCurrentDirectoryInPath: # new in 1.53
  Enabled: true
Style/RedundantFilterChain: # new in 1.52
  Enabled: true
Style/RedundantRegexpArgument: # new in 1.53
  Enabled: true
Style/RedundantRegexpConstructor: # new in 1.52
  Enabled: true
Style/ReturnNilInPredicateMethodDefinition: # new in 1.53
  Enabled: false
Style/YAMLFileRead: # new in 1.53
  Enabled: true
RSpec/ReceiveMessages: # new in 2.23
  Enabled: true
Performance/MapMethodChain: # new in 1.19
  Enabled: true
Lint/LiteralAssignmentInCondition: # new in 1.58
  Enabled: true
Style/SingleLineDoEndBlock: # new in 1.57
  Enabled: true
Style/SuperWithArgsParentheses: # new in 1.58
  Enabled: true
RSpec/EmptyMetadata: # new in 2.24
  Enabled: true
RSpec/Eq: # new in 2.24
  Enabled: true
RSpec/MetadataStyle: # new in 2.24
  Enabled: true
RSpec/SpecFilePathFormat: # new in 2.24
  Enabled: false
RSpec/SpecFilePathSuffix: # new in 2.24
  Enabled: false
Lint/ItWithoutArgumentsInBlock: # new in 1.59
  Enabled: true
RSpec/RedundantPredicateMatcher: # new in 2.26
  Enabled: true
RSpec/RemoveConst: # new in 2.26
  Enabled: true
RSpec/IsExpectedSpecify: # new in 2.27
  Enabled: true
RSpec/RepeatedSubjectCall: # new in 2.27
  Enabled: true
Style/MapIntoArray: # new in 1.63
  Enabled: true
RSpec/EmptyOutput: # new in 2.29
  Enabled: true
RSpec/UndescriptiveLiteralsDescription: # new in 2.29
  Enabled: true
Style/SendWithLiteralMethodName: # new in 1.64
  Enabled: true
Style/SuperArguments: # new in 1.64
  Enabled: false
RSpec/ExpectInLet: # new in 2.30
  Enabled: true
Gemspec/AddRuntimeDependency: # new in 1.65
  Enabled: true
Lint/UselessNumericOperation: # new in 1.66
  Enabled: true
Style/RedundantInterpolationUnfreeze: # new in 1.66
  Enabled: true
